# -*- coding: utf-8 -*-
"""Naives Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGd7k1hqQ_fM8VIkyI0HYeYBWesTfLuD

08/09/2023
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv("/content/naivebayes.csv")
dataset

X = dataset.iloc[:,0:2].values
Y = dataset.iloc[:,2].values

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.20)

X_train

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

X_train

from sklearn.naive_bayes import BernoulliNB
classifierBNB = BernoulliNB()
classifierBNB.fit(X_train,Y_train)

Y_pred = classifierBNB.predict(X_test)

Y_pred

from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

from sklearn.naive_bayes import GaussianNB
classifierGNB = GaussianNB()
classifierGNB.fit(X_train,Y_train)

Y_pred = classifierGNB.predict(X_test)

Y_pred

from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)